# Generated by Django 5.0 on 2024-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_photo'),
        ),
    ]
