# Generated by Django 5.0 on 2024-08-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0002_userprofilemodel_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='email',
            new_name='username',
        ),
    ]
