# Generated by Django 5.0 on 2024-08-21 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0004_userassetmodel_userfundingmodel_userwalletmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfundingmodel',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='funding'),
        ),
        migrations.AlterField(
            model_name='userfundingmodel',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
