# Generated by Django 5.0 on 2024-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0005_userfundingmodel_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfundingmodel',
            name='payment_crypto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfundingmodel',
            name='payment_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
