# Generated by Django 5.0 on 2024-08-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_supportedcryptomodel'),
        ('user_site', '0006_userfundingmodel_payment_crypto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfundingmodel',
            name='payment_crypto',
        ),
        migrations.AddField(
            model_name='userfundingmodel',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.supportedcryptomodel'),
        ),
    ]
