# Generated by Django 5.0 on 2024-08-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0008_alter_userfundingmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfundingmodel',
            name='previous_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userfundingmodel',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='images/funding'),
        ),
    ]
