# Generated by Django 5.0 on 2024-08-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0009_userfundingmodel_previous_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletmodel',
            name='mining_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
