# Generated by Django 5.0 on 2024-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_assetmodel'),
        ('user_site', '0011_assetmodel_userwatchlistmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetModel',
        ),
        migrations.AlterField(
            model_name='userwatchlistmodel',
            name='watch_lists',
            field=models.ManyToManyField(blank=True, to='admin_site.assetmodel'),
        ),
    ]
