# Generated by Django 5.0 on 2024-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0013_assetconversionmodel_assetvaluemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetconversionmodel',
            name='direction',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assetconversionmodel',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetvaluemodel',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
