# Generated by Django 5.0 on 2024-08-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0014_alter_assetconversionmodel_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='identity_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='assetconversionmodel',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
