# Generated by Django 5.0 on 2024-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0015_userprofilemodel_address_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='last_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
