# Generated by Django 5.0 on 2024-08-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0016_userprofilemodel_last_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address_verification_pending',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='identity_verification_pending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
