# Generated by Django 5.0 on 2024-08-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0017_userprofilemodel_address_verification_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address_document',
            field=models.FileField(blank=True, null=True, upload_to='profile/verification'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='profile/verification'),
        ),
    ]
