# Generated by Django 5.0 on 2024-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0018_userprofilemodel_address_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='identity_document',
            new_name='identity_document_1',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='identity_document_2',
            field=models.FileField(blank=True, null=True, upload_to='profile/verification'),
        ),
    ]
