# Generated by Django 5.0 on 2024-08-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0019_rename_identity_document_userprofilemodel_identity_document_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletmodel',
            name='referral_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
