# Generated by Django 5.0 on 2024-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0020_userwalletmodel_referral_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='has_deposited',
            field=models.BooleanField(default=False),
        ),
    ]
