# Generated by Django 5.0 on 2024-08-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_rename_duration_in_days_miningplanmodel_duration'),
        ('user_site', '0021_userprofilemodel_has_deposited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='trade_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.tradingplanmodel'),
        ),
    ]
