# Generated by Django 5.0 on 2024-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0024_usertrademodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrademodel',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
