# Generated by Django 5.0 on 2024-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0025_usertrademodel_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrademodel',
            name='close_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usertrademodel',
            name='open_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
