# Generated by Django 5.0 on 2024-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0026_usertrademodel_close_value_usertrademodel_open_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrademodel',
            name='direction',
            field=models.CharField(default='up', max_length=10),
        ),
    ]
