# Generated by Django 5.0 on 2024-08-29 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0027_usertrademodel_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithdrawalMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('address_number', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWithdrawalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('wallet_type', models.CharField(choices=[('holding', 'HOLDING BALANCE'), ('trading', 'TRADING BALANCE'), ('referral', 'REFERRAL BONUS')], max_length=30)),
                ('payment_address', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_value', models.FloatField(blank=True, null=True)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='images/funding')),
                ('status', models.CharField(blank=True, default='pending', max_length=30)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_site.userwithdrawalmethodmodel')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
