# Generated by Django 5.0 on 2024-08-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0028_userwithdrawalmethodmodel_userwithdrawalmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwithdrawalmodel',
            old_name='payment_number',
            new_name='payment_name',
        ),
    ]
