# Generated by Django 5.0 on 2024-08-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0029_rename_payment_number_userwithdrawalmodel_payment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwithdrawalmodel',
            name='payment_value',
        ),
    ]
