# Generated by Django 5.0 on 2024-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0030_remove_userwithdrawalmodel_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfundingmodel',
            name='other_payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'BANK TRANSFER'), ('paypal', 'PAYPAL'), ('venmo', 'VENMO'), ('cash app', 'CASH APP'), ('payoneer', 'PAYONEER'), ('zelle', 'ZELLE')], max_length=20, null=True),
        ),
    ]
