# Generated by Django 5.0 on 2024-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('asset', models.CharField(max_length=100)),
                ('duration_in_days', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('active', 'ACTIVE')], default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SignalPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('strength', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('active', 'ACTIVE')], default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('pairs', models.IntegerField()),
                ('leverage', models.IntegerField()),
                ('pip', models.IntegerField()),
                ('has_swap_fee', models.BooleanField()),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('active', 'ACTIVE')], default='active', max_length=30)),
            ],
        ),
    ]
