# Generated by Django 5.0 on 2024-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningplanmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='signalplanmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='tradingplanmodel',
            name='pip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradingplanmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30),
        ),
    ]
