# Generated by Django 5.0 on 2024-08-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_miningplanmodel_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miningplanmodel',
            old_name='duration_in_days',
            new_name='duration',
        ),
    ]
