# Generated by Django 5.0 on 2024-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_currencymodel_sitesettingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencymodel',
            name='symbol',
            field=models.CharField(default='$', max_length=10),
            preserve_default=False,
        ),
    ]
