# Generated by Django 5.0 on 2024-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_currencymodel_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='minimum_deposit',
            field=models.FloatField(default=50),
        ),
    ]
