# Generated by Django 5.0 on 2024-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_sitesettingmodel_minimum_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='swap_fee',
            field=models.FloatField(default=0.05),
        ),
    ]
