# Generated by Django 5.0 on 2024-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_sitesettingmodel_swap_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='default_funding_account',
            field=models.CharField(choices=[('holding', 'HOLDING BALANCE'), ('trading', 'TRADING BALANCE')], default='holding', max_length=30),
            preserve_default=False,
        ),
    ]
