# Generated by Django 5.0 on 2024-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_supportedcryptomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcryptomodel',
            name='address',
            field=models.CharField(default='ftfyguhigytdrdfyt', max_length=250),
            preserve_default=False,
        ),
    ]
