# Generated by Django 5.0 on 2024-08-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_supportedcryptomodel_old_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcryptomodel',
            name='barcode',
            field=models.FileField(blank=True, null=True, upload_to='barcode/address'),
        ),
    ]
