# Generated by Django 5.0 on 2024-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_assetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='category',
            field=models.CharField(default='crypto', max_length=50),
        ),
    ]
