# Generated by Django 5.0 on 2024-08-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0012_assetmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='referral_bonus',
            field=models.FloatField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='referral_payment_before_bonus',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
