# Generated by Django 5.0 on 2024-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0013_sitesettingmodel_referral_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingmodel',
            name='referral_payment_before_bonus',
            field=models.BooleanField(default=True),
        ),
    ]
