# Generated by Django 5.0 on 2024-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_sitesettingmodel_minimum_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='minimum_trade_amount',
            field=models.FloatField(default=5),
        ),
    ]
