# Generated by Django 5.0 on 2024-08-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0017_sitesettingmodel_trade_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='default_max_leverage',
            field=models.FloatField(blank=True, default=10),
        ),
    ]
