# Generated by Django 5.0 on 2024-08-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0018_sitesettingmodel_default_max_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='minimum_withdrawal',
            field=models.FloatField(default=50),
        ),
    ]
