# Generated by Django 5.0 on 2024-09-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0019_sitesettingmodel_minimum_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportedcryptomodel',
            name='code',
        ),
    ]
