# Generated by Django 5.0 on 2024-12-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0020_remove_supportedcryptomodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='template',
            field=models.CharField(choices=[('1', 'TEMPLATE ONE'), ('2', 'TEMPLATE TWO')], default='1', max_length=10),
        ),
    ]
