# Generated by Django 5.0 on 2024-12-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0021_sitesettingmodel_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('transfer', 'BANK TRANSFER'), ('paypal', 'PAYPAL'), ('venmo', 'VENMO'), ('cash app', 'CASH APP'), ('payoneer', 'PAYONEER'), ('zelle', 'ZELLE')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.EmailField(max_length=50)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10)),
            ],
        ),
    ]
