# Generated by Django 5.0 on 2024-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0022_paymentmodemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodemodel',
            options={'ordering': ['category'], 'verbose_name': 'Payment Mode', 'verbose_name_plural': 'Payment Modes'},
        ),
        migrations.RemoveField(
            model_name='paymentmodemodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='category',
            field=models.CharField(choices=[('transfer', 'BANK TRANSFER'), ('paypal', 'PAYPAL'), ('venmo', 'VENMO'), ('cash_app', 'CASH APP'), ('payoneer', 'PAYONEER'), ('zelle', 'ZELLE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
    ]
