# Generated by Django 5.0 on 2024-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0023_alter_paymentmodemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodemodel',
            name='category',
            field=models.CharField(choices=[('transfer', 'BANK TRANSFER'), ('paypal', 'PAYPAL'), ('venmo', 'VENMO'), ('cash app', 'CASH APP'), ('payoneer', 'PAYONEER'), ('zelle', 'ZELLE')], max_length=20),
        ),
    ]
